name: mp_tic_tak_toe
description: A new Flutter Multiplayer TIK TAK TOE app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  google_fonts: ^4.0.4
  awesome_notifications: ^0.7.4+1
  flutter_local_notifications: ^15.1.0+1
  dio: ^5.3.4
  socket_io_client: ^2.0.3+1
  provider: ^6.1.2
  share_plus: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

